config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tools do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [ :destroy, :index, :show ]
  resources :users, only: [ :show ]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_one_attached :photo
  has_many :bookings
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true, inclusion: {in: ["Home Improvement", "Automotive", "Gardening", "Cleaning"]}
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tools
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
  end

  def create
    @now = Date.today
    @booking = Booking.new(booking_params)
    @booking.tool = Tool.find(params[:tool_id])
    @booking.user = current_user
    if @booking.start_date >= @now && @booking.start_date <= @booking.end_date && @booking.save
      redirect_to dashboard_path
    else
      redirect_to tool_path(@booking.tool)
      flash.now[:notice] = "A problem has occurred while processing your booking."
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private 

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def dashboard
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:query].present?
      sql = "tools.name ILIKE :query OR tools.description ILIKE :query" 
      @tools = Tool.where(sql, query: "%#{params[:query]}%")
    else
      @tools = Tool.all
    end
    @tools = Tool.geocoded
    @markers = @tools.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude
      }
    end
  end

  def new
    @tool = Tool.new
    @category = ["Home Improvement", "Gardening", "Automotive", "Cleaning"]
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tools_path(@user)
    else
      render :new
    end
  end

  def show
    @tool = Tool.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @tool.latitude,
      lng: @tool.longitude,
      }]
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    redirect_to dashboard_path
  end

  def update
    @tool = Tool.find(params[:id])

    if @tool.update(tool_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :category, :address, :description, :user_id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenToolBox</title>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🔨</text></svg>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%= render 'shared/homenavbar' %>
<div class="tools-container">
<br>
<br>
<br>
<div class="my-dashboard" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(/assets/dashboard.jpg)">
  My Dashboard
</div>

<div class="listings-and-bookings">
  <div class="container-bookings col-6">
    <h2>My Bookings</h2>
    <% current_user.bookings.each do |booking| %>
      <div class="card-product">
        <% if booking.tool.photo.attached? %>
          <%= cl_image_tag booking.tool.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img height="300" width="400" crop="fill" src="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1581705325-41z1obml8il-ac-1581705279.jpg"/>
        <% end %>
        <div class="card-product-infos ml-1">
          <h2><%= booking.tool.name %></h2>
          <p>From:   <strong><%= booking.start_date %></strong></p><br>
          <p>To:   <strong><%= booking.end_date %></strong></p><br>
          <p><strong>£29/day</strong><p><br>
          <p><%= link_to 'Cancel this booking', booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      </div>
    <% end %>
  </div>
  <!---comment--->
  <div class="container-tools col-6">
    <h2>My Tools</h2>
    <h5><%=link_to "List a new tool", new_tool_path, class: "btn btn-primary" %></h5>
    <br>

    <div class="card-product">
      <% current_user.tools.each do |tool| %>
        <% if tool.photo.attached? %>
          <%= cl_image_tag tool.photo.key, height: 320, width: 400, crop: :fill %>
        <% else %>
          <img src="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1581705325-41z1obml8il-ac-1581705279.jpg"/>
        <% end %>

        <div class="card-product-infos ml-1">
          <h2><%= tool.name %></h2>
          <p><em><%= tool.description %></em></p>
          <div class="links mt-3">
            <p><%= link_to 'Edit', edit_tool_path(tool) %></p>
            <p><%= link_to 'Delete', tool_path(tool), method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </div>
        </div>

      <% end %>
      <br>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<%= render 'shared/homenavbar' %>
<div class="grad-bg">
  <header class=toolbox>
    <div class="toolbox-central text-center">
      <h1 class="mx-auto my-0 text-uppercase">Open Tool Box</h1>
      <h2 class="text-white-50 mx-auto mt-2 mb-5"></h2>
      <%= link_to "Rent Tools", tools_path, class: "btn btn-primary" %>
    </div>
  </header>
  <div class="carousel_container">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner" role="listbox" style=" width:100%; height: 100vh;">
        <div class="carousel-item active">
          <%= image_tag 'home_improvement.jpg', class: "d-block w-100", alt: "First slide"%>
            <div class="carousel-caption">
              <h5></h5>
              <p></p>
            </div>
        </div>
        <div class="carousel-item">
          <%= image_tag 'gardening.jpg', class: "d-block w-100", alt: "Second slide"%>
            <div class="carousel-caption" class="text-left">
              <h5></h5>
              <p></p>
            </div>
        </div>
        <div class="carousel-item">
          <%= image_tag 'automotive.jpg', class: "d-block w-100", alt: "Third slide"%>
            <div class="carousel-caption">
              <h5></h5>
              <p></p>
            </div>
        </div>
        <div class="carousel-item">
          <%= image_tag 'cleaning.jpg', class: "d-block w-100", alt: "Fourth slide"%>
            <div class="carousel-caption">
              <h5></h5>
              <p></p>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!--
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     <i class=""></i>
  </div>
</div>
-->

app/views/shared/_homenavbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://www.geniushub.co.uk/wp-content/uploads/spanner-01.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon other-pages">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://www.geniushub.co.uk/wp-content/uploads/spanner-01.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatarnew.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/tools/edit.html.erb
<%= render 'shared/homenavbar' %>
<br>
<div class="form">
  <h1>Edit Tool Info</h1>
  <%= simple_form_for(@tool) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn-primary" %>
  <% end %>
  <p><%= link_to ('<i class="fas fa-home" style="color: #E6B831"></i>').html_safe, tools_path %><p>
</div>

app/views/tools/index.html.erb
<%= render 'shared/homenavbar' %>
<br><br>
<div class="tools-container">

  <h1>A Tool For Any Situation</h1>
  <br>
  <div class="search-form">
    <%= form_tag tools_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Please enter a tool...."
      %>
      <br>
      <%= submit_tag "Search", class: "btn btn-primary-index" %>
    <% end %>
  </div>
  <br><br><br>
  <div class="card-container">
    <div class="tools">
      <% @tools.each do |tool| %>
        <div class="card-trip">
          <%= link_to tool_path(tool) do %>
            <% if tool.photo.attached? %>
              <%= cl_image_tag tool.photo.key, height: 300, width: 400, crop: :fill %>
            <% else %>
              <img height="300" width="400" src="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1581705325-41z1obml8il-ac-1581705279.jpg">
            <% end %>
          <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= tool.name.capitalize %></h2>
                <p><%= tool.description %></p>
              </div>
              <h2 class="card-trip-pricing">£29</h2>
              <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
            </div>
        </div>
      <% end %>
    </div>
    <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/tools/new.html.erb
<%= render 'shared/homenavbar' %>
<div class="form">
  <h2> List a Tool </h2>
  <%= simple_form_for(@tool) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.input :photo, as: :file %>
    <br>
    <%= f.input :address %>
    <%= f.input :category, as: :select, collection: @category, prompt: 'Select category', label: false %>
    <%= f.submit class: "btn-primary" %>
  <% end %>

  <p><%= link_to ('<i class="fas fa-home"></i>').html_safe, tools_path, class: "icon-yellow" %></p>
</div>

app/views/tools/show.html.erb
<%= render 'shared/navbar' %>
  <br>
  <h1>Tool Hire</h1>

  <div class="second-container">
      <br>
      <h2><%= @tool.name %></h2>
      <div class="show-item-container">
        <div class="tool-show-card">
          <div class="image">
            <% if @tool.photo.attached? %>
              <%= cl_image_tag @tool.photo.key, height: 320, width: 400, crop: :fill %>
            <% else %>
              <img height="320" width="400" src="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1581705325-41z1obml8il-ac-1581705279.jpg">
            <% end %>
          </div>
          <div class="info">
            <p><i class="fas fa-tools"></i> <%= @tool.description %></p>

            <div class="price">
              <h4>£29 per day</h4>
            </div>
          </div>
        </div>
        <div class="booking-form">
          <h3>Create a new booking</h3>

          <%= simple_form_for [@tool, @booking] do |f| %>
            <div class="form-inputs">
              <%= f.input :start_date, as: :date, html5: true  %>
              <%= f.input :end_date, as: :date, html5: true  %>
            </div>

            <div class="form-actions btn">
              <%= f.button :submit, class: "btn btn-primary-booking" %>
            </div>
        <% end %>
      </div>
    </div>

    <div id="map"
        style="width: 100%; height: 320px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="links">
      <%= link_to ('<i class="fas fa-arrow-circle-left"></i> Go back').html_safe, tools_path, class: "btn btn-outline" %>
      <!--
      <p><%= link_to edit_tool_path(@tool) do  %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to ('<i class="fas fa-trash"></i>').html_safe, tool_path(@tool), method: :delete, data: { confirm: "Are you sure you want to delete " + @tool.name } %>
      </p>
      -->
    </div>
  

app/views/users/show.html.erb
<% @user.tools.each do |tool| %>

<% end %>